ts_module(
    name = "copperkey",
    src = "index.ts",
    deps = ["//copperkey/components:button"],
    visibility = ["PUBLIC"]
)

sass_file(
    name = "base_sass",
    src = "base.scss",
    visibility = ["PUBLIC"],
)

sass_file(
    name = "variables_sass",
    src = "variables.scss",
    visibility = ["PUBLIC"],
)
