esbuild_bundle(
    name = "ops",
    entry = "index.tsx",
    plugins = [
        "//build/js:esbuild_sass_plugin",
    ],
    deps = [
        "//third_party/js:react",
        "//third_party/js:react-dom",
        "//ops/src:page"
    ]
)

